"""
EconoCausal - Causal ML Model

Purpose:
    Estimate the causal effect of receiving a discount treatment
    on customer purchase probability using Double Machine Learning.

Causal Question:
    Does receiving a discount increase the probability that a
    customer makes a purchase?

Current status:
    Skeleton / interface definition.
    Full model fitting will be implemented on Day 3.

Pipeline:
    Dataset
        ↓
    config.yaml
        ↓
    preprocessing.py
        ↓
    LinearDML
        ↓
    Estimated Treatment Effects (ITE)
        ↓
    causal_output.csv
"""


# -------------------------------------------------------------------
# Project configuration
# -------------------------------------------------------------------

DATA_PATH = "data/econocausal_dataset.csv"
CONFIG_PATH = "causal_ml/config.yaml"

# Expected model configuration:
#
# Treatment:
#     treatment_received
#
# Outcome:
#     purchase
#
# Confounders (W):
#     historical_revenue
#     historical_orders
#     avg_order_value
#     days_since_last_purchase
#     website_visits
#     email_opens
#     email_clicks
#     previous_campaign_response
#     customer_segment
#
# Covariates (X):
#     age
#     tenure_months


# -------------------------------------------------------------------
# Causal variables
# -------------------------------------------------------------------

# T = treatment
# Y = outcome
# W = observed confounders
# X = additional covariates


# -------------------------------------------------------------------
# Preprocessing
# -------------------------------------------------------------------

# preprocessing.py will:
#
# 1. Load and validate the dataset.
# 2. Read treatment/outcome/confounders/covariates from config.yaml.
# 3. Encode categorical variables such as customer_segment.
# 4. Ensure model inputs are numeric.
# 5. Separate:
#       T = treatment
#       Y = outcome
#       W = confounders
#       X = covariates
#
# model.py will call these preprocessing functions rather than
# requiring preprocessing.py to be executed manually.


# -------------------------------------------------------------------
# Causal Model
# -------------------------------------------------------------------

# EconML LinearDML will be used with:
#
#     model_y = LightGBM
#     model_t = LightGBM
#     discrete_treatment = True
#
# Treatment:
#     treatment_received ∈ {0, 1}
#
# Outcome:
#     purchase ∈ {0, 1}


# -------------------------------------------------------------------
# Ground-truth variables
# -------------------------------------------------------------------

# The following columns are generated by the synthetic data
# generator and must NOT be used as model inputs:
#
#     true_baseline_purchase_probability
#     true_treatment_purchase_probability
#     true_ite
#     true_treatment_probability
#
# They are retained only for evaluating the estimated causal effects
# after model training.


# -------------------------------------------------------------------
# Post-treatment variables
# -------------------------------------------------------------------

# The following variables must NOT be used as confounders/covariates:
#
#     purchase_value
#     discount_cost
#     net_revenue
#
# discount_percentage is also excluded from the initial binary
# treatment model because treatment_received represents whether
# treatment was received. A future analysis may model discount
# intensity separately.


# -------------------------------------------------------------------
# Model output
# -------------------------------------------------------------------

# The fitted model will eventually produce:
#
#     customer_id
#     estimated_control_outcome
#     estimated_treated_outcome
#     estimated_ite
#
# estimated_ite will later be compared against the generator's
# true_ite for model evaluation.


# -------------------------------------------------------------------
# Day 3 TODO
# -------------------------------------------------------------------

# TODO:
# 1. Load config.yaml.
# 2. Load dataset.
# 3. Call preprocessing.py.
# 4. Initialize LinearDML.
# 5. Fit model.
# 6. Estimate individual treatment effects.
# 7. Generate causal_output.csv.
# 8. Evaluate estimated_ite against true_ite.